#!/bin/bash

python src/termExtraction/word_features.py $1 goodList.url
python src/termExtraction/word_features.py $1 badList.url

./runOctaveSet $1

./webSearch $1

./jsonStrip data/$1/urls/newUrlList.res data/$1/urls/newUrlList.url

python src/termExtraction/word_features.py $1 newUrlList.url

./generateClassification $1